/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.projects.dashboard.business.unit.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectBU service. Represents a row in the &quot;PD_ProjectBU&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.projects.dashboard.business.unit.model.impl.ProjectBUModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.projects.dashboard.business.unit.model.impl.ProjectBUImpl}.
 * </p>
 *
 * @author Yury Butrymovich
 * @see ProjectBU
 * @see com.liferay.projects.dashboard.business.unit.model.impl.ProjectBUImpl
 * @see com.liferay.projects.dashboard.business.unit.model.impl.ProjectBUModelImpl
 * @generated
 */
@ProviderType
public interface ProjectBUModel extends BaseModel<ProjectBU>, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project b u model instance should use the {@link ProjectBU} interface instead.
	 */

	/**
	 * Returns the primary key of this project b u.
	 *
	 * @return the primary key of this project b u
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project b u.
	 *
	 * @param primaryKey the primary key of this project b u
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project b u.
	 *
	 * @return the uuid of this project b u
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this project b u.
	 *
	 * @param uuid the uuid of this project b u
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project b u ID of this project b u.
	 *
	 * @return the project b u ID of this project b u
	 */
	public long getProjectBUId();

	/**
	 * Sets the project b u ID of this project b u.
	 *
	 * @param projectBUId the project b u ID of this project b u
	 */
	public void setProjectBUId(long projectBUId);

	/**
	 * Returns the company ID of this project b u.
	 *
	 * @return the company ID of this project b u
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project b u.
	 *
	 * @param companyId the company ID of this project b u
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project b u.
	 *
	 * @return the user ID of this project b u
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project b u.
	 *
	 * @param userId the user ID of this project b u
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project b u.
	 *
	 * @return the user uuid of this project b u
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project b u.
	 *
	 * @param userUuid the user uuid of this project b u
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project b u.
	 *
	 * @return the user name of this project b u
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project b u.
	 *
	 * @param userName the user name of this project b u
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project b u.
	 *
	 * @return the create date of this project b u
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project b u.
	 *
	 * @param createDate the create date of this project b u
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project b u.
	 *
	 * @return the modified date of this project b u
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project b u.
	 *
	 * @param modifiedDate the modified date of this project b u
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the business unit ID of this project b u.
	 *
	 * @return the business unit ID of this project b u
	 */
	public long getBusinessUnitId();

	/**
	 * Sets the business unit ID of this project b u.
	 *
	 * @param businessUnitId the business unit ID of this project b u
	 */
	public void setBusinessUnitId(long businessUnitId);

	/**
	 * Returns the project ID of this project b u.
	 *
	 * @return the project ID of this project b u
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project b u.
	 *
	 * @param projectId the project ID of this project b u
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the type of this project b u.
	 *
	 * @return the type of this project b u
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this project b u.
	 *
	 * @param type the type of this project b u
	 */
	public void setType(String type);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectBU projectBU);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectBU> toCacheModel();

	@Override
	public ProjectBU toEscapedModel();

	@Override
	public ProjectBU toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}