/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.projects.dashboard.problem.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AuditedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Problem service. Represents a row in the &quot;PD_Problem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.projects.dashboard.problem.model.impl.ProblemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.projects.dashboard.problem.model.impl.ProblemImpl}.
 * </p>
 *
 * @author Howie Chou
 * @see Problem
 * @see com.liferay.projects.dashboard.problem.model.impl.ProblemImpl
 * @see com.liferay.projects.dashboard.problem.model.impl.ProblemModelImpl
 * @generated
 */
@ProviderType
public interface ProblemModel extends AuditedModel, BaseModel<Problem>,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a problem model instance should use the {@link Problem} interface instead.
	 */

	/**
	 * Returns the primary key of this problem.
	 *
	 * @return the primary key of this problem
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this problem.
	 *
	 * @param primaryKey the primary key of this problem
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the problem ID of this problem.
	 *
	 * @return the problem ID of this problem
	 */
	public long getProblemId();

	/**
	 * Sets the problem ID of this problem.
	 *
	 * @param problemId the problem ID of this problem
	 */
	public void setProblemId(long problemId);

	/**
	 * Returns the company ID of this problem.
	 *
	 * @return the company ID of this problem
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this problem.
	 *
	 * @param companyId the company ID of this problem
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this problem.
	 *
	 * @return the user ID of this problem
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this problem.
	 *
	 * @param userId the user ID of this problem
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this problem.
	 *
	 * @return the user uuid of this problem
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this problem.
	 *
	 * @param userUuid the user uuid of this problem
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this problem.
	 *
	 * @return the user name of this problem
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this problem.
	 *
	 * @param userName the user name of this problem
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this problem.
	 *
	 * @return the create date of this problem
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this problem.
	 *
	 * @param createDate the create date of this problem
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this problem.
	 *
	 * @return the modified date of this problem
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this problem.
	 *
	 * @param modifiedDate the modified date of this problem
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project ID of this problem.
	 *
	 * @return the project ID of this problem
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this problem.
	 *
	 * @param projectId the project ID of this problem
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the type of this problem.
	 *
	 * @return the type of this problem
	 */
	public int getType();

	/**
	 * Sets the type of this problem.
	 *
	 * @param type the type of this problem
	 */
	public void setType(int type);

	/**
	 * Returns the description of this problem.
	 *
	 * @return the description of this problem
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this problem.
	 *
	 * @param description the description of this problem
	 */
	public void setDescription(String description);

	/**
	 * Returns the status of this problem.
	 *
	 * @return the status of this problem
	 */
	public int getStatus();

	/**
	 * Sets the status of this problem.
	 *
	 * @param status the status of this problem
	 */
	public void setStatus(int status);

	/**
	 * Returns the status date of this problem.
	 *
	 * @return the status date of this problem
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this problem.
	 *
	 * @param statusDate the status date of this problem
	 */
	public void setStatusDate(Date statusDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Problem problem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Problem> toCacheModel();

	@Override
	public Problem toEscapedModel();

	@Override
	public Problem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}